PF-UTN/ManagementPortal-FE

- projects/common-ui/src/lib/components/index.ts
- projects/common-ui/src/lib/components/loading/loading.component.html
- projects/common-ui/src/lib/components/loading/loading.component.scss
- projects/common-ui/src/lib/components/loading/loading.component.ts
- projects/common-ui/src/lib/components/table/table.component.html
- projects/common-ui/src/lib/components/table/table.component.scss
- projects/common-ui/src/lib/components/table/table.component.ts
- projects/common-ui/src/lib/models/table-column.model.ts
- projects/product/src/lib/components/product-list/product-list.component.html
- projects/registration-request/src/lib/component/registration-request-list/registration-request-list.component.html
- projects/registration-request/src/lib/component/registration-request-list/registration-request-list.component.ts
- src/index.html
- src/styles/_varibles.scss
> [MP-226] Rebranding table component

- projects/authentication/src/lib/components/signup/signup.component.html
- projects/authentication/src/lib/components/signup/signup.component.spec.ts
- projects/authentication/src/lib/components/signup/signup.component.ts
- projects/common/src/models/client.model.ts
- projects/common/src/models/town-item.model.ts
- projects/common/src/models/town-param.model.ts
- projects/common/src/services/town/town.service.spec.ts
- projects/common/src/services/town/town.service.ts
- projects/common/src/testing/mock-data.model.ts
- projects/supplier/src/lib/components/create-update-supplier-lateral-drawer/create-update-supplier-lateral-drawer.component.ts
Sujeta a la aprobación de la [PR #75 del backend](https://github.com/PF-UTN/ManagementPortal-BE/pull/75).
> [MP-264] Fix: Update client birthdate field and town search integration

- projects/authentication/src/lib/components/signup/signup.component.ts
> [MP-357] Validate town input to allow only selection from the list

- projects/common-ui/src/lib/components/dropdown-button/dropdown-button.component.html
- projects/common-ui/src/lib/components/dropdown-button/dropdown-button.component.scss
- projects/common-ui/src/lib/components/dropdown-button/dropdown-button.component.ts
- projects/product/src/lib/components/product-list/product-list.component.html
- projects/product/src/lib/components/product-list/product-list.component.scss
- src/styles.scss
- src/styles/_varibles.scss
> [MP-366] Refactor style of product list page

- projects/product-category/src/public-api.ts
- projects/product/src/lib/components/product-list/product-list.component.html
- projects/product/src/lib/components/product-list/product-list.component.spec.ts
- projects/product/src/lib/components/product-list/product-list.component.ts
- projects/supplier/src/lib/services/supplier.service.ts
- projects/supplier/src/public-api.ts
Filters Category, Supplier and Enable were added to product list
> [MP-161] ProductList filters

- projects/common-ui/src/lib/components/index.ts
- projects/common-ui/src/lib/components/pill/index.ts
- projects/common-ui/src/lib/components/pill/models/pill.status.model.ts
- projects/common-ui/src/lib/components/pill/pill.component.html
- projects/common-ui/src/lib/components/pill/pill.component.scss
- projects/common-ui/src/lib/components/pill/pill.component.ts
- projects/common-ui/src/lib/components/table/table.component.html
- projects/common-ui/src/lib/components/table/table.component.spec.ts
- projects/common-ui/src/lib/components/table/table.component.ts
- projects/common-ui/src/lib/constants/column-types.constant.ts
- projects/common-ui/src/lib/models/column-types.model.ts
- projects/common-ui/src/lib/models/table-column.model.ts
- projects/registration-request/src/lib/component/registration-request-list/registration-request-list.component.ts
- src/styles/_varibles.scss
> [MP-498] pill columns for tables

- projects/common-ui/src/lib/components/list/list.component.ts
- projects/purchase-order/src/lib/components/detail-lateral-drawer/detail-lateral-drawer.component.html
- projects/purchase-order/src/lib/components/detail-lateral-drawer/detail-lateral-drawer.component.scss
- projects/purchase-order/src/lib/components/detail-lateral-drawer/detail-lateral-drawer.component.spec.ts
- projects/purchase-order/src/lib/components/detail-lateral-drawer/detail-lateral-drawer.component.ts
- projects/purchase-order/src/lib/components/purchase-order-list/purchase-order-list.component.spec.ts
- projects/purchase-order/src/lib/components/purchase-order-list/purchase-order-list.component.ts
- projects/purchase-order/src/lib/models/purchase-order-detail.model.ts
- projects/purchase-order/src/lib/services/purchase-order.service.spec.ts
- projects/purchase-order/src/lib/services/purchase-order.service.ts
- projects/purchase-order/src/lib/testing/mock-data.model.ts
Feat: Lateral Drawer Purchase Order Detail
> [MP-331] Lateral Drawer Purchase Order Detail

- projects/common-ui/src/lib/components/back-arrow/back-arrow.component.scss
- projects/vehicle/src/lib/components/maintenance-history/maintenance-history.component.html
- projects/vehicle/src/lib/components/maintenance-history/maintenance-history.component.scss
- projects/vehicle/src/lib/components/maintenance-history/maintenance-history.component.spec.ts
- projects/vehicle/src/lib/components/maintenance-history/maintenance-history.component.ts
- projects/vehicle/src/lib/components/maintenance-list/maintenance-list.component.html
- projects/vehicle/src/lib/components/maintenance-list/maintenance-list.component.spec.ts
- projects/vehicle/src/lib/components/maintenance-list/maintenance-list.component.ts
- projects/vehicle/src/lib/components/maintenance-plan-list/maintenance-plan-list.component.html
- projects/vehicle/src/lib/components/maintenance-plan-list/maintenance-plan-list.component.spec.ts
- projects/vehicle/src/lib/components/maintenance-plan-list/maintenance-plan-list.component.ts
- projects/vehicle/src/lib/components/maintenance-repair-list/maintenance-repair-list.component.html
- projects/vehicle/src/lib/components/maintenance-repair-list/maintenance-repair-list.component.spec.ts
- projects/vehicle/src/lib/components/maintenance-repair-list/maintenance-repair-list.component.ts
- projects/vehicle/src/lib/models/maintenance-plan.model.ts
- projects/vehicle/src/lib/vehicle-routing.module.ts
> [MP-396]Add maintenance history component

- projects/purchase-order/src/lib/components/purchase-order-list/purchase-order-list.component.spec.ts
- projects/purchase-order/src/lib/components/purchase-order-list/purchase-order-list.component.ts
- projects/purchase-order/src/lib/constants/purchase-order-status.enum.ts
> [MP-508] Bug Purchase Order List

- projects/purchase-order/src/lib/components/purchase-order-list/purchase-order-list.component.ts
- projects/purchase-order/src/lib/constants/purchase-order-status.enum.ts
Solo se puden cancelar ordenes de compra en estado Borrador o Pedida
> [MP-593] Add cancellation status check for purchase orders

- projects/product/src/lib/components/product-card/product-card.component.html
- projects/product/src/lib/components/product-created/product-create.component.spec.ts
- projects/product/src/lib/components/product-created/product-create.component.ts
- projects/product/src/lib/components/product-list/product-list.component.html
- projects/product/src/lib/components/product-list/product-list.component.ts
> [MP-420]Multiple fixes

- projects/product/src/lib/components/detail-lateral-drawer/detail-lateral-drawer.component.html
- projects/product/src/lib/components/detail-lateral-drawer/detail-lateral-drawer.component.scss
- projects/product/src/lib/components/detail-lateral-drawer/detail-lateral-drawer.component.ts
> [MP-622] Refactor product detail layout

- projects/authentication/src/lib/components/signup/signup.component.html
- projects/authentication/src/lib/components/signup/signup.component.scss
- projects/authentication/src/lib/components/signup/signup.component.ts
> [MP-454] Add logo signup

- projects/vehicle/src/lib/components/create-maintenance-plan/create-maintenance-plan.component.html
- projects/vehicle/src/lib/components/create-maintenance-plan/create-maintenance-plan.component.spec.ts
- projects/vehicle/src/lib/components/create-maintenance-plan/create-maintenance-plan.component.ts
- projects/vehicle/src/lib/components/create-update-maintenance-item-drawer/create-update-maintenance-item-lateral-drawer.component.html
- projects/vehicle/src/lib/components/create-update-maintenance-item-drawer/create-update-maintenance-item-lateral-drawer.component.spec.ts
- projects/vehicle/src/lib/components/create-update-maintenance-item-drawer/create-update-maintenance-item-lateral-drawer.component.ts
- projects/vehicle/src/lib/models/maintenance-item-create.model.ts
- projects/vehicle/src/lib/models/maintenance-item-update.model.ts
- projects/vehicle/src/lib/models/maintenance-plan-create.model.ts
- projects/vehicle/src/lib/services/vehicle.service.spec.ts
- projects/vehicle/src/lib/services/vehicle.service.ts
> [MP-562] creación modificación de ítem de mantenimiento

- projects/cart/src/lib/components/cart-detail/cart-detail.component.html
- projects/cart/src/lib/components/cart-detail/cart-detail.component.spec.ts
- projects/cart/src/lib/components/cart-detail/cart-detail.component.ts
- projects/product/src/lib/components/detail-lateral-client-drawer/detail-lateral-client-drawer.component.spec.ts
- projects/product/src/lib/components/detail-lateral-client-drawer/detail-lateral-client-drawer.component.ts
- projects/product/src/lib/components/product-list-client/product-list-client.component.spec.ts
- projects/product/src/lib/components/product-list-client/product-list-client.component.ts
> [MP-716] Cart Improvements

- projects/vehicle/src/lib/components/maintenance-plan-list/maintenance-plan-list.component.spec.ts
- projects/vehicle/src/lib/components/maintenance-plan-list/maintenance-plan-list.component.ts
- projects/vehicle/src/lib/components/perform-maintenance-plan/perform-maintenance-plan.component.html
- projects/vehicle/src/lib/components/perform-maintenance-plan/perform-maintenance-plan.component.scss
- projects/vehicle/src/lib/components/perform-maintenance-plan/perform-maintenance-plan.component.spec.ts
- projects/vehicle/src/lib/components/perform-maintenance-plan/perform-maintenance-plan.component.ts
- projects/vehicle/src/lib/models/maintenance-perform.model.ts
- projects/vehicle/src/lib/models/supplier-search-response-model.ts
- projects/vehicle/src/lib/services/vehicle.service.spec.ts
- projects/vehicle/src/lib/services/vehicle.service.ts
- projects/vehicle/src/lib/vehicle-routing.module.ts
> [MP-581] Implement Perform Maintenance Plan

- projects/vehicle/src/lib/components/perform-maintenance-plan/perform-maintenance-plan.component.html
- projects/vehicle/src/lib/components/perform-maintenance-plan/perform-maintenance-plan.component.ts
> [MP-718] Update supplier creation option

- projects/vehicle/src/lib/components/maintenance-history/maintenance-history.component.html
- projects/vehicle/src/lib/components/maintenance-history/maintenance-history.component.scss
- projects/vehicle/src/lib/components/maintenance-history/maintenance-history.component.ts
- projects/vehicle/src/lib/components/maintenance-list/maintenance-list.component.spec.ts
- projects/vehicle/src/lib/components/maintenance-list/maintenance-list.component.ts
- projects/vehicle/src/lib/components/maintenance-plan-list/maintenance-plan-list.component.spec.ts
- projects/vehicle/src/lib/components/maintenance-plan-list/maintenance-plan-list.component.ts
- projects/vehicle/src/lib/models/maintenance-item.model.ts
> [MP-694] Add column next maintenance

- projects/order/src/lib/components/order-list/order-list.component.html
- projects/order/src/lib/components/order-list/order-list.component.spec.ts
- projects/order/src/lib/components/order-list/order-list.component.ts
- projects/order/src/lib/models/order-params.model.ts
- projects/order/src/lib/services/order.service.spec.ts
- projects/purchase-order/src/lib/components/purchase-order-list/purchase-order-list.component.html
- projects/purchase-order/src/lib/components/purchase-order-list/purchase-order-list.component.spec.ts
- projects/purchase-order/src/lib/components/purchase-order-list/purchase-order-list.component.ts
Fix: Order and Purchase Order List Bugs
> [MP-776] [MP-782] Download Order List And Fix Invalid Dates in Date Filters PO And O

- projects/order/src/lib/components/order-list-client/order-list-client.component.ts
- projects/order/src/lib/components/order-list/order-list.component.ts
- projects/product/src/lib/components/product-list/product-list.component.ts
- projects/registration-request/src/lib/component/registration-request-list/registration-request-list.component.ts
- projects/vehicle/src/lib/components/maintenance-list/maintenance-list.component.ts
- projects/vehicle/src/lib/components/maintenance-plan-list/maintenance-plan-list.component.ts
- projects/vehicle/src/lib/components/maintenance-repair-list/maintenance-repair-list.component.ts
- projects/vehicle/src/lib/components/vehicle-list/vehicle-list.component.ts
Feat: MP-625 Unificar titulos columnas tablas
> [MP-625] Unificar titulos columnas tablas

- projects/order/src/lib/components/detail-lateral-drawer/detail-lateral-drawer.component.html
- projects/order/src/lib/components/detail-lateral-drawer/detail-lateral-drawer.component.scss
- projects/order/src/lib/components/detail-lateral-drawer/detail-lateral-drawer.component.spec.ts
- projects/order/src/lib/components/detail-lateral-drawer/detail-lateral-drawer.component.ts
- projects/order/src/lib/components/order-list/order-list.component.ts
- projects/order/src/lib/models/order-detail.model.ts
- projects/order/src/lib/services/order.service.spec.ts
- projects/order/src/lib/services/order.service.ts
- projects/order/src/lib/testing/mock-data.model.ts
Feat: Order Detail Lateral Drawer
> [MP-669] Order Detail Lateral Drawer

- projects/authentication/src/lib/components/login/login.component.html
- projects/authentication/src/lib/components/login/login.component.ts
- projects/authentication/src/lib/components/signup/signup.component.html
- projects/authentication/src/lib/components/signup/signup.component.ts
- projects/common-ui/src/lib/components/auth-title/auth-title.component.html
- projects/common-ui/src/lib/components/auth-title/auth-title.component.scss
- projects/common-ui/src/lib/components/auth-title/auth-title.component.spec.ts
- projects/common-ui/src/lib/components/auth-title/auth-title.component.ts
- projects/common-ui/src/lib/components/index.ts
- projects/order/src/lib/components/order-list-client/order-list-client.component.html
- projects/order/src/lib/components/order-list-client/order-list-client.component.ts
- projects/order/src/lib/components/order-list/order-list.component.html
- projects/order/src/lib/components/order-list/order-list.component.ts
- projects/product/src/lib/components/product-list-client/product-list-client.component.html
- projects/product/src/lib/components/product-list-client/product-list-client.component.scss
- projects/product/src/lib/components/product-list-client/product-list-client.component.spec.ts
- projects/product/src/lib/components/product-list-client/product-list-client.component.ts
- projects/product/src/lib/components/product-list/product-list.component.html
- projects/purchase-order/src/lib/components/purchase-order-list/purchase-order-list.component.html
- projects/purchase-order/src/lib/components/purchase-order-list/purchase-order-list.component.ts
- projects/registration-request/src/lib/component/registration-request-list/registration-request-list.component.html
- projects/vehicle/src/lib/components/vehicle-list/vehicle-list.component.html
- src/app/components/nav-bar/nav-bar.component.scss
> [MP-788] Arreglos varios FE
